config/routes.rb
Rails.application.routes.draw do

  root 'cats#new'

  resources :cats

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  def magic8
["You will find a bushel of money", "Your smile will tell you what makes you feel good", "Don’t panic", "The best year-round temperature is a warm heart and a cool head", "It could be better, but it’s good enough.", "You will find a thing. It may be important","Your reality check about to bounce.","Two days from now, tomorrow will be yesterday.","Stop eating now. Food poisoning no fun.","You are cleverly disguised as responsible adult.","Drive like hell, you will get there.","Okay to look at past and future. Just don’t stare.","You will soon have an out of money experience.","The end is near, might as well have dessert.","Marriage lets you annoy one special person for the rest of your life","I cannot help you, for I’m just a cookie","Come back later….I’m sleeping (yes, cats need their sleep too)","In times of tech trouble, restart computer","NoMethodError"].sample

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end
 helper_method :magic8


  def magic8
  ["You will find a bushel of money", "Your smile will tell you what makes you feel good", "Don’t panic", "The best year-round temperature is a warm heart and a cool head", "It could be better, but it’s good enough.", "You will find a thing. It may be important","Your reality check about to bounce.","Two days from now, tomorrow will be yesterday.","Stop eating now. Food poisoning no fun.","You are cleverly disguised as responsible adult.","Drive like hell, you will get there.","Okay to look at past and future. Just don’t stare.","You will soon have an out of money experience.","The end is near, might as well have dessert.","Marriage lets you annoy one special person for the rest of your life","I cannot help you, for I’m just a cookie","Come back later….I’m sleeping (yes, cats need their sleep too)","In times of tech trouble, restart computer"].sample

  end


  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:question, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<body class="center">

    <h1>Your Fortune</h1>
   <h2> " <%= magic8 %> "</h2>

  <h1>Your Luckycat</h1>


<%= image_tag("cat#{rand(7)}.jpg") %>

  <h1>  </h1>
<%= link_to 'Get another lucky fortune!', new_cat_path, :class => "btn"  %>

</body>

app/views/cats/new.html.erb
<body class="center">

<title>LuckyCat Fortune</title>

<!-- <%= render 'form' %> -->

<h1> Get your fortune told by Luckycat </h1>

  
  <%= image_tag("logo.jpg") %>
 

  <h1> What's your question? </h1>

  <form>

<input class="question" type="text", placeholder='Question pls!' >

</form>

<%= link_to 'Get Lucky', cats_path,:class => "btn" %>

</body>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @cat.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @cat.answer %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luckycat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>